name: scraping-jurisprudencia

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10']

    steps:

      - uses: actions/checkout@v2

      - name: Build using Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing dependencies
        run: |
          python -m pip install pip --upgrade pip
          pip install pipenv
          make setup

      - name: Checking code style
        run: |
          make check_style

      - name: Running tests
        run: |
          make tests